cua/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('', views.index, name='index'),
]

cua/mod/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import secrets
import string

# Create your models here.

class IDClass():
	def newID():
		choice_set = string.ascii_uppercase + string.digits
		newID = ""
		while newID == "":
			for i in range(24):
				chosen = secrets.choice(choice_set)
				newID += chosen
		return newID

class Tag(models.Model):
	name = models.CharField(primary_key=True, max_length=128, editable=True)
	creation_date = models.DateTimeField(default=timezone.now)
	creator = models.ForeignKey(User, default=None, null=True, blank=True, on_delete=models.SET_NULL)

	def __str__(self):
		return f'{self.name}'

class Item(models.Model):
	id = models.CharField(primary_key=True, default=IDClass.newID, max_length=12, editable=False)
	name = models.CharField(max_length=128)
	former_name = models.CharField(max_length=128, null=True, blank=True, default=None)
	description = models.CharField(max_length=512)
	former_description = models.CharField(max_length=512, null=True, blank=True, default=None)
	file = models.FileField(upload_to="files/{0}".format(IDClass.newID()), null=True, blank=True)
	video = models.CharField(max_length=16, null=True, blank=True)
	repo = models.CharField(max_length=128, null=True, blank=True)
	creation_date = models.DateTimeField(default=timezone.now)
	creator = models.ForeignKey(User, default=None, null=True, blank=True, on_delete=models.SET_DEFAULT)
	tags = models.ManyToManyField(Tag)


	def __str__ (self):
		return f'{self.name}'

class Item_Request(models.Model):
	id = models.CharField(primary_key=True, default=IDClass.newID, max_length=12, editable=False)
	name = models.CharField(max_length=128)
	description = models.CharField(max_length=512)
	file = models.FileField(upload_to="files/{0}".format(IDClass.newID()), null=True, blank=True)
	video = models.CharField(max_length=11, null=True, blank=True)
	repo = models.CharField(max_length=128, null=True, blank=True)
	creation_date = models.DateTimeField(default=timezone.now)
	creator = models.ForeignKey(User, default=None, null=True, blank=True, on_delete=models.SET_DEFAULT)
	tags = models.ManyToManyField(Tag)


	def __str__ (self):
		return f'{self.name}'

cua/index/templates/index/base.html
{% load staticfiles%}
{% load tags %}
<!DOCTYPE html>
<link rel="stylesheet" type="text/css" href="{% static 'index/base.css' %}" async>
<html>

<head>
    <meta charset="utf-8">
    <meta name="publisuites-verify-code" content="aHR0cHM6Ly9jb21wYXJ0aWRvc3VhLmVzLw==" />
    <title>CompartidosUA</title>
    <link rel="icon" href="{% static 'index/favicon.png' %}" type="image/png">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" async></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.5/umd/popper.min.js" defer></script>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" async rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" defer></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({
        google_ad_client: "ca-pub-8673495335982040",
        enable_page_level_ads: true
    });
    </script>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-137195994-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-137195994-1');
    </script>

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light">
        <a class="navbar-brand" href="{% url 'index' %}">
            <img src="{% static 'index/favicon.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            CompartidosUA
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'upload' %}">Subir</a>
                </li>
                <form action="{% url 'results' %}" method="get" class="form-inline my-2 my-lg-0" style="flex-flow:row!important;">
                    {% csrf_token %}
                    <input type="text" name="query" class="form-control" placeholder="Tema a buscar" aria-label="Tema a buscar" aria-describedby="button-search">
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="input" id="button-search">Buscar</button>
                    </div>
                </form>
            </ul>
        </div>
    </nav>
    <div class="container-full">
        {% block body_block %}
        {% endblock %}
        <div class="jumbotron text-center">
            <h1>Apoya a CompartidosUA</h1>
            <p class="lead">Este proyecto comunitario no se podría llevar a cabo sin tu ayuda. Por favor, considera una pequeña donación a CompartidosUA para seguir trayéndote material de calidad, libre y sin anuncios.</p>
            <p><a class="btn btn-large btn-patreon" href="https://www.patreon.com/CUA" target="ext">Patreon</a></p>
        </div>
    </div> <!-- /container full -->
</body>

</html>

cua/index/templates/index/details.html
{% extends "index/base.html" %}
{% block body_block %}
{% load staticfiles%}
<div class="jumbotron text-center">
    <script type="text/javascript">
    var TxtRotate = function(el, toRotate, period) {
        this.toRotate = toRotate;
        this.el = el;
        this.loopNum = 0;
        this.period = parseInt(period, 10) || 2000;
        this.txt = 'ompartidos';
        this.tick();
        this.isDeleting = true;
    };

    TxtRotate.prototype.tick = function() {
        var i = this.loopNum % this.toRotate.length;
        var fullTxt = this.toRotate[i];

        if (this.isDeleting) {
            this.txt = fullTxt.substring(0, this.txt.length - 1);
        } else {
            this.txt = fullTxt.substring(0, this.txt.length + 1);
        }

        this.el.innerHTML = '<span class="wrap">' + this.txt + '</span>';

        var that = this;
        var delta = 300 - Math.random() * 100;

        if (this.isDeleting) { delta /= 2; }

        if (!this.isDeleting && this.txt === fullTxt) {
            delta = this.period;
            this.isDeleting = true;
        } else if (this.isDeleting && this.txt === '') {
            this.isDeleting = false;
            this.loopNum++;
            delta = 500;
        }

        setTimeout(function() {
            that.tick();
        }, delta);
    };

    window.onload = function() {
        var elements = document.getElementsByClassName('txt-rotate');
        for (var i = 0; i < elements.length; i++) {
            var toRotate = elements[i].getAttribute('data-rotate');
            var period = elements[i].getAttribute('data-period');
            if (toRotate) {
                new TxtRotate(elements[i], JSON.parse(toRotate), period);
            }
        }
        // INJECT CSS
        var css = document.createElement("style");
        css.type = "text/css";
        css.innerHTML = ".txt-rotate > .wrap { border-right: 0.08em solid #666 }";
        document.body.appendChild(css);
    };
    </script>
    <h1>C<span class="txt-rotate" data-period="2000" data-rotate='[ "ompartidos", "rea", "omunica", "onfia", "onstruye", "opia", "alcula", "olabora", "ita", "elebra" ]'>
        </span>UA
    </h1>
    <p class="lead">Tu web de apuntes, ejercicios y soluciones</p>
    <form action="{% url 'results' %}" method="get" class="input-group mb-3">
        {% csrf_token %}
        <input name="query" type="text" class="form-control" placeholder="Introduce tu tema a buscar" aria-label="Introduce tu tema a buscar" aria-describedby="button-search">
        <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="submit" id="button-search">Buscar</button>
        </div>
    </form>
</div>
<div class="container">
    <div class="jumbotron text-center">
        <h1>{{ item.name }}</h1>
        <p class="lead">{{ item.description|linebreaks }}</p>
        {% if item.file %}<p><a class="btn btn-large btn-success" href="{% url 'download' item_id=item.id %}" download>Descargar</a></p>
        {% elif item.video %}<iframe width="560" height="315" src="https://www.youtube.com/embed/{{ item.video }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        {% elif item.repo %}<a href="https://www.github.com/{{ item.repo }}">Repositorio</a></script>
        {% endif %}
    </div>
</div>
<hr>
{% endblock %}

cua/index/templates/index/index.html
{% extends "index/base.html" %}
{% block body_block %}
{% load staticfiles%}
<div class="jumbotron text-center">
    <script type="text/javascript">
    var TxtRotate = function(el, toRotate, period) {
        this.toRotate = toRotate;
        this.el = el;
        this.loopNum = 0;
        this.period = parseInt(period, 10) || 2000;
        this.txt = 'ompartidos';
        this.tick();
        this.isDeleting = true;
    };

    TxtRotate.prototype.tick = function() {
        var i = this.loopNum % this.toRotate.length;
        var fullTxt = this.toRotate[i];

        if (this.isDeleting) {
            this.txt = fullTxt.substring(0, this.txt.length - 1);
        } else {
            this.txt = fullTxt.substring(0, this.txt.length + 1);
        }

        this.el.innerHTML = '<span class="wrap">' + this.txt + '</span>';

        var that = this;
        var delta = 300 - Math.random() * 100;

        if (this.isDeleting) { delta /= 2; }

        if (!this.isDeleting && this.txt === fullTxt) {
            delta = this.period;
            this.isDeleting = true;
        } else if (this.isDeleting && this.txt === '') {
            this.isDeleting = false;
            this.loopNum++;
            delta = 500;
        }

        setTimeout(function() {
            that.tick();
        }, delta);
    };

    window.onload = function() {
        var elements = document.getElementsByClassName('txt-rotate');
        for (var i = 0; i < elements.length; i++) {
            var toRotate = elements[i].getAttribute('data-rotate');
            var period = elements[i].getAttribute('data-period');
            if (toRotate) {
                new TxtRotate(elements[i], JSON.parse(toRotate), period);
            }
        }
        // INJECT CSS
        var css = document.createElement("style");
        css.type = "text/css";
        css.innerHTML = ".txt-rotate > .wrap { border-right: 0.08em solid #666 }";
        document.body.appendChild(css);
    };
    </script>
    <h1>C<span class="txt-rotate" data-period="2000" data-rotate='[ "ompartidos", "rea", "omunica", "onfia", "onstruye", "opia", "alcula", "olabora", "ita", "elebra" ]'>
        </span>UA
    </h1>
    <p class="lead">Tu web de apuntes, ejercicios y soluciones</p>
    <form action="{% url 'results' %}" method="get" class="input-group mb-3">
        {% csrf_token %}
        <input name="query" type="text" class="form-control" placeholder="Introduce tu tema a buscar" aria-label="Introduce tu tema a buscar" aria-describedby="button-search">
        <div class="input-group-append">
            <button class="btn btn-outline-secondary" type="submit" id="button-search">Buscar</button>
        </div>
    </form>
</div>
<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <h4>Codigo libre</h4>
            <p>Todo el código es público en el <a href="https://github.com/Imphinium/cua">repositorio oficial</a></p>
            <h4>Comunitario</h4>
            <p>La plataforma CompartidosUA está enteramente administrada por la comunidad.</p>
        </div>
        <div class="col-lg-6">
            <h4>Privada</h4>
            <p>Tus datos de descargas nunca serán rastreados y podrás subir tus documentos anónimamente</p>
            <h4>Menos mierda</h4>
            <p>Sabemos que estas aqui por los apuntes, así que toda la página está dedicada a ellos</p>
        </div>
    </div>
</div>
<hr>
{% endblock %}

cua/index/templates/index/results.html
{% extends "index/base.html" %}
{% block body_block %}
{% load staticfiles %}
{% load octicons %}
<div class="container">
    <div class="list-group">
        {% for item in results %}
        <a href="#" onclick="location.href='{% url 'details' item_id=item.id %}';" class="list-group-item list-group-item-action flex-column align-items-start ">
            <div class="row justify-content-start align-items-center">
                <div class="col-1">
                {% if item.file %}{% octicon "file-zip" heigth="64" width="64" %}
                {% elif item.video %}{% octicon "device-camera-video" heigth="64" width="64" %}
                {% elif item.repo %}{% octicon "git-branch" heigth="64" width="64" %}
                {% endif %}
            </div>
                <div class="col">
                    <h5 class="mb-1">{{ item.name }}</h5>
                    <p class="mb-1">{{ item.description }}</p>
                    <h6>{% for tag in item.tags.all %}<div onclick="location.href='{% url 'results' %}?tags={{ tag }}';event.stopPropagation();" class="badge badge-primary">{{ tag }}</div> {% endfor %}</h6>
                </div>
                <div class="col-2 ml-auto d-flex flex-column">
                    <small class="text-center">{{ item.creation_date|timesince }}</small><br>
                    {% if item.file %}<div class="btn btn-large btn-success p-2" onclick="location.href='{% url 'download' item_id=item.id %}';event.stopPropagation();" download>Descargar</div>
                    {% elif item.video %}<div class="btn btn-large btn-success p-2">Ver</div>
                    {% elif item.repo %}<div class="btn btn-large btn-success p-2">Repositorio</div>
                    {% endif %}
                </div>
            </div>
        </a>
        {% endfor %}
        {% if not results %}
        <div class="jumbotron container">
            <div class="d-flex flex-sm-row flex-column-reverse">
                <div class="col-lg-6 align-self-center no-lp">
                    <h3 class="mb-1">Lo sentimos</h3>
                    <p class="mb-1">No se han encontrado resultados para su búsqueda</p>
                </div>
                <div class="col-lg-6 no-lp">
                    <img src="{% static 'index/sadbot.svg' %}" style="max-height:200px;">
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>
<hr>
{% endblock %}

cua/index/templates/index/upload.html
{% extends "index/base.html" %}
{% block body_block %}
{% load staticfiles%}
<link rel="stylesheet" type="text/css" href="{% static 'index/upload.css' %}" async>
<div class="jumbotron text-center">
    <script type="text/javascript">
    var TxtRotate = function(el, toRotate, period) {
        this.toRotate = toRotate;
        this.el = el;
        this.loopNum = 0;
        this.period = parseInt(period, 10) || 2000;
        this.txt = 'ompartidos';
        this.tick();
        this.isDeleting = true;
    };

    TxtRotate.prototype.tick = function() {
        var i = this.loopNum % this.toRotate.length;
        var fullTxt = this.toRotate[i];

        if (this.isDeleting) {
            this.txt = fullTxt.substring(0, this.txt.length - 1);
        } else {
            this.txt = fullTxt.substring(0, this.txt.length + 1);
        }

        this.el.innerHTML = '<span class="wrap">' + this.txt + '</span>';

        var that = this;
        var delta = 300 - Math.random() * 100;

        if (this.isDeleting) { delta /= 2; }

        if (!this.isDeleting && this.txt === fullTxt) {
            delta = this.period;
            this.isDeleting = true;
        } else if (this.isDeleting && this.txt === '') {
            this.isDeleting = false;
            this.loopNum++;
            delta = 500;
        }

        setTimeout(function() {
            that.tick();
        }, delta);
    };

    window.onload = function() {
        var elements = document.getElementsByClassName('txt-rotate');
        for (var i = 0; i < elements.length; i++) {
            var toRotate = elements[i].getAttribute('data-rotate');
            var period = elements[i].getAttribute('data-period');
            if (toRotate) {
                new TxtRotate(elements[i], JSON.parse(toRotate), period);
            }
        }
        // INJECT CSS
        var css = document.createElement("style");
        css.type = "text/css";
        css.innerHTML = ".txt-rotate > .wrap { border-right: 0.08em solid #666 }";
        document.body.appendChild(css);
    };
    </script>
    <h1>C<span class="txt-rotate" data-period="2000" data-rotate='[ "ompartidos", "rea", "omunica", "onfia", "onstruye", "opia", "alcula", "olabora", "ita", "elebra" ]'>
        </span>UA
    </h1>
    <p class="lead">Tu web de apuntes, ejercicios y soluciones</p>
    <form enctype="multipart/form-data" id="id_ajax_upload_form" method="POST" novalidate="" class="text-justify">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_name">Nombre</label>
            <input type="text" class="form-control" id="id_name" aria-describedby="nameHelp" placeholder="Introduce un nombre corto y explicativo" name="name" required>
            <small id="nameHelp" class="form-text text-muted">Puede ser el nombre de la práctica, e incluir identificadores como el tema o la asignatura</small>
        </div>
        <div class="form-group">
            <label for="id_tags">Tags</label><br>
            <span id="tagContainer"></span>
            <input type="text" class="form-control" id="id_tags" aria-describedby="nameHelp" placeholder="Introduce las tags separadas por espacios" name="tags" required>
            <small id="tagsHelp" class="form-text text-muted">Deben de ser los temas con los que se relaciona tu contrinución, por ejemplo MD, Calculo, IngInf1, Multimedia3</small>
            {# Atento la función esta está de putísima madre cuando cargas jQuery asíncronamente. Cuidao #}
            <script type="text/javascript">
            function tags_defer() {
                if (window.jQuery) { //{# Esta función comprueba las tags y las formatea bonitas #}
                    $(document).ready(function() {
                        $("#id_tags").keyup(function(event) {
                            let arr = $(this).val().split(" ")
                            $("#tagContainer").empty()
                            for (i in arr) {
                                $("#tagContainer").append('   <span class="badge badge-info">' + (arr[i]) + '</span>');
                            }
                        });
                    });
                } else {
                    setTimeout(function() { tags_defer() }, 50);
                }
            }
            tags_defer();
            </script>
        </div>
        <div class="form-group">
            <label for="id_description">Descripción</label>
            <textarea class="form-control" id="id_description" rows="3" name="description" required></textarea>
            <small id="descHelp" class="form-text text-muted">Asegurate de explicar los contenidos de los apuntes. Puedes introducir tu nombre o alguna tag para identificarlo fácilmente mas tarde</small>
        </div>
        <nav>
            <div class="nav nav-tabs" id="nav-tab" role="tablist">
                <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Archivo</a>
                <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Repositorio</a>
                <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false">Vídeo</a>
            </div>
        </nav>
        <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                <div class="form-group">
                    <label for="id_file">Archivo</label>
                    <input type="file" class="form-control-file" id="id_file" name="file" required>
                </div>
            </div>
            <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
                <label for="id_repo">Repositorio</label><br>
                <input type="text" class="form-control" id="id_repo" aria-describedby="nameHelp" placeholder="Usuario/Repositorio" name="repo" required>
                <small id="repoHelp" class="form-text text-muted">Debe de estar en formato "{Usuario}/{Repositorio}". Por ejemplo, Imphinium/cua</small>
                <script type="text/javascript">
                function repo_defer() {
                    if (window.jQuery) { //{# Esta función comprueba que el repositorio exista #}
                        $(document).ready(function() {
                            $("#id_repo").on("keyup", function(event) {
                                var request = new XMLHttpRequest()
                                request.open('GET', 'https://api.github.com/repos/' + $("#id_repo").val(), true)
                                request.onload = function() {
                                    console.log(request.status)
                                    if (request.status == 404) {
                                        $("#id_repo").removeClass("is-valid")
                                        $("#id_repo").addClass("is-invalid")
                                    } else if (request.status == 200) {
                                        $("#id_repo").removeClass("is-invalid")
                                        $("#id_repo").addClass("is-valid")
                                    } else {
                                        $("#repoHelp").text("No se puede contactar con GitHub ahora mismo. Lo cual no quiere decir que el repositorio no exista, sino que has superado las 60 querys gratuitas a la hora. Intentalo mas tarde o envíalo y deja que el servidor compruebe la autenticidad del repo.")
                                    }
                                }
                                request.send()
                            });
                        });
                    } else {
                        setTimeout(function() { tags_defer() }, 50);
                    }
                }
                repo_defer();
                </script>
            </div>
            <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
                <label for="id_video">Video de Youtube</label><br>
                <input type="text" class="form-control" id="id_video" aria-describedby="nameHelp" placeholder="Introduce la ID del video" name="video" required>
                <small id="videoHelp" class="form-text text-muted">La ID es lo que va en "watch?v={ID}". Por ahora solo aceptamos vídeos de YT</small>
                <script type="text/javascript">
                function vides_defer() {
                    if (window.jQuery) { //{# Esta función comprueba que el repositorio exista #}
                        $(document).ready(function() {
                            $("#id_video").on("keyup", function(event) {
                                var img = new Image();
                                img.src = 'http://img.youtube.com/vi/' + $("#id_video").val() + '/mqdefault.jpg'
                                img.onload = function() {
                                    console.log(this.width)
                                    if (this.width === 120) {
                                        $("#id_video").removeClass("is-valid")
                                        $("#id_video").addClass("is-invalid")
                                    } else if (this.width === 320) {
                                        $("#id_video").removeClass("is-invalid")
                                        $("#id_video").addClass("is-valid")
                                    } else {
                                        $("#repoHelp").text("Se ha detectado un error no reconocido. ¿Que has hecho, pilluel@? :/")
                                    }
                                }
                            });
                        });
                    } else {
                        setTimeout(function() { tags_defer() }, 50);
                    }
                }
                vid_defer();
                </script>
            </div>
        </div>
        <script type="text/javascript">
        function tab_defer() {
            if (window.jQuery) { //{# Esta función comprueba que el repositorio exista #}
                $(document).ready(function() {
                    $('[data-toggle="tab"]').on("click", function(event) {
                        console.log("a")
                        $("#id_video").val("")
                        $("#id_video").removeClass("is-valid")
                        $("#id_video").removeClass("is-invalid")

                        $("#id_repo").val("")
                        $("#id_repo").removeClass("is-valid")
                        $("#id_repo").removeClass("is-invalid")

                        $("#id_file").val("")
                    });
                });
            } else {
                setTimeout(function() { tags_defer() }, 50);
            }
        }
        tab_defer();
        </script>
        <input type="submit" />
    </form>
    <script type="text/javascript">
    // form upload
    $('#id_ajax_upload_form').submit(function(e) {
        e.preventDefault();
        $form = $(this)
        var formData = new FormData(this);
        $.ajax({
            url: window.location.pathname,
            type: 'POST',
            data: formData,
            success: function(response) {
                $('.error').remove();
                console.log(response)
                if (response.error) {
                    $.each(response.errors, function(name, error) {
                        error = '<small class="text-muted error">' + error + '</small>'
                        $form.find('[name=' + name + ']').after(error);
                    })
                } else {
                    alert(response.message)
                    window.location = ""
                }
            },
            cache: false,
            contentType: false,
            processData: false
        });
    });
    // end
    </script>
</div>
{% endblock %}